session_id: "20260224-143137-549ecc3ac6bcdbf2"
created_at: "2026-02-24T13:31:37Z"
status: "COMPLETED"
title: "Research REGN financials.
  Use latest available filings and earnings materials.
  Return:
  1) Revenue, operating incom"
