session_id: "20260224-143346-0617fcee79429c42"
created_at: "2026-02-24T13:33:46Z"
status: "COMPLETED"
title: "Research REGN financials.
    Use latest available filings and earnings materials.
    Return:
    1) Revenue, operating"
